<?php
$sitemapPage = $this->sitemapPage;
$indexSlides = $this->indexSlides;
$news = $this->news;
$services = $this->services;
$servicesSitemapPage = $this->servicesSitemapPage;
$photoGalleries = $this->photoGalleries;
$photoGalleriesPages = $this->photoGalleriesPages;
$products = $this->products;
$suppliersName= $this->suppliersName;
$productsOnAction = $this->productsOnAction;
$productsByDateAded = $this->productsByDateAded;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<article class="container-fluid slide_carusel">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="6000" data-pause="hover">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php for ($carousel = 0; $carousel < count($this->indexSlides); $carousel++) { ?>
                <li 
                    data-target="#carousel-example-generic" 
                    data-slide-to="<?php echo $carousel; ?>" <?php echo $carousel == 0 ? "class=\"active\"" : ''; ?>>
                </li>
            <?php } ?>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $carouselInner = 0;
            foreach ($this->indexSlides as $indexSlide) { ?>
                <div class="item <?php echo $carouselInner == 0 ? "active" : "";
                $carouselInner++; ?>">
                    <img class="img-responsive" src="<?php echo $this->indexSlideImgUrl($indexSlide); ?>" alt="" />

                    <div class="carousel-caption">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        <h2><?php echo $this->escape($indexSlide['title']); ?></h2>
                    </div>
                    <div class="carousel-caption-right">
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                    </div>
                </div>
<?php } ?>
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

                <span class="sr-only">Next</span>
            </a>
        </div>

</article>
<main>
<!--    <section class="search">
        <div class="container">
            <form method="POST" >
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" placeholder="Type here the name of spare parts, model car or VIN-code">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Find goods</button>
                    </span>
                </div>
            </form>
            <p>For example: <span>Сute cars parts </span> or <span> Cute-cute parts</span></p>
        </div>
    </section>-->

    <section class="container cars">
        <div class="owl-carousel">
<?php foreach ($this->suppliers as $supplier) { ?>
                <div class="item">
                    <img src="<?php echo $this->supplierImgUrl($supplier); ?>" alt=""/>
                </div>

<?php } ?>
        </div>
    </section>



    <section class="container goods">
        <div class="row">
            <div class="col-md-12 buttons">
                <button type="button" class="btn btn-primary down-arrow">On Action</button>
            </div>

<?php foreach ($productsOnAction as $product) {
    ?>
                <div class="col-sm-6 col-md-4 col-lg-3 <?php echo $this->escape($product['model']); ?>" >

                    <article class="items center-block" >

                        <figure>
                            <a href="<?php echo $this->productItemUrl($product); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/></a>
                            <figcaption>
                                <a href="<?php echo $this->productItemUrl($product); ?>"> <h3><?php echo $this->escape($product['type']); ?></h3></a>
                                <p><?php echo $this->escape($product['model']); ?></p>
                                <button type="button" class="btn"><?php echo $this->escape($product['price']); ?></button>
                            </figcaption>

                        </figure>
                    </article>

                </div>
<?php }
?>
            
            <div class="col-xs-12 showMore"></div>
            <div class="col-md-12 buttons">
            <button type="button" class="btn btn-primary down-arrow">New Products</button>
            </div>
            <?php foreach ($productsByDateAded as $product) {
    ?>
                <div class="col-sm-6 col-md-4 col-lg-3 <?php echo $this->escape($product['model']); ?>" >

                    <article class="items center-block" >

                        <figure>
                            <a href="<?php echo $this->productItemUrl($product); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/></a>
                            <figcaption>
                                <a href="<?php echo $this->productItemUrl($product); ?>"> <h3><?php echo $this->escape($product['type']); ?></h3></a>
                                <p><?php echo $this->escape($product['model']); ?></p>
                                <button type="button" class="btn"><?php echo $this->escape($product['price']); ?></button>
                            </figcaption>

                        </figure>
                    </article>

                </div>
<?php }
?>
            <div class="col-xs-12 showMore"></div>
            <!--            <div class="col-xs-12 showMore">
                            <a href="#"><span class="glyphicon glyphicon-chevron-down"></span>Show 12 more goods</a>
                        </div>-->
        </div>

    </section>
    <section class="soldParts">
        <div class="transparentColor">
            <div class="container">
                <div  class="row">
<?php foreach ($products as $product) {
    ?>
                        <article class="col-xs-6 col-md-3 text-center">
                            <h3><?php echo $this->escape($product['quantity']); ?></h3>
                            <p><?php echo $this->escape($product['model'] . ' ' . $product['type']); ?></p>

                        </article>
<?php }
?>
                </div>
            </div>
        </div>
    </section>
    <section class="news">
        <div class="container">
            <h3 class="text-center">NEWS <br><?php if ($this->newsSitemapPage) { ?>
                    <small><a href="<?php echo $this->sitemapPageUrl($this->newsSitemapPage['id']); ?>">View all</a></small>
<?php } ?></h3>

            <div class="row">
                <div class="col-xs-10">
                    <div class="slider"><!-- The slider -->
                        <div><!-- A mandatory div used by the slider -->
                            <!-- Each div below is considered a slide -->
<?php foreach ($news as $oneNews) {
    ?>
                                <div>
                                    <figure class="newsItem">
                                        <div class="imgNews">
                                            <img class="img-responsive" src="<?php echo $this->newsImgUrl($oneNews); ?>" alt=""/>
                                            <!--                                        <div class="hoverNews text-center">
                                                                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                                                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                                                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                                                                    </div>-->
                                        </div>

                                        <figcaption>
                                            <h4><?php echo $this->escape($oneNews['title']); ?></h4>
    <!--                                        <button type="button" class="btn items date"><?php echo $this->escape($oneNews['date']); ?></button>-->
                                            <a href="<?php echo $this->itemUrl($oneNews); ?>" target="_blank"><button type="button" class="btn items article">Read More</button></a>
                                            <p><?php echo $this->escape($oneNews['description']); ?></p>

                                        </figcaption>
                                    </figure>
                                </div>
<?php }
?>
                        </div>

                    </div>
                </div>
                <div class="col-xs-2 controlsNews">

                    <span id="go-left" class="glyphicon glyphicon-menu-left"></span>
                    <span id="go-right" class="glyphicon glyphicon-menu-right"></span>

                </div>
            </div>
        </div>
    </section>
    <section class="cuteParts">
        <div class="transparentColor">
            <div class="container">
                <div  class="row">
                    <article class="tuningCenter col-md-6">
                        <h4><img src="<?php echo $this->baseUrl('/img/logo_dark.png'); ?>" alt=""/>Cute parts</h4>
                        <h3>Tuning Center</h3>
                        <p>Acquiring and loading a Tune License into your Power Vision is quicker and easier than before. 
                            Simply launch WinPV, click on the PV Online icon, and in a few steps you’re ready to tune.
                            If you need additional Tune Licenses, simply log into your account and purchase them.
                            Every step of the process is now handled online, at your convenience.  </p>

                    </article>
                </div>
            </div>
            <div class="pumpRide text-center"><?php if ($this->servicesSitemapPage) { ?><a href="<?php echo $this->sitemapPageUrl($this->servicesSitemapPage['id']); ?>"><h3>Pump your ride with our services  <span class="fa fa-arrow-right"></span></h3></a><?php } ?></div>


        </div>
    </section>
    <section class="pumpOptions">

        <div class="container">
<?php foreach ($services as $service) {
    ?> 
                <div class="row">

                    <div class="col-sm-6 col-md-3">
                        <article class="part center-block">

                            <figure>
                                <h3 class="title">

                                </h3>
                                <figcaption class="text-center">
                                    <h3><i class="<?php echo $this->escape($service['icon']); ?>"></i> <?php echo $this->escape($service['title']); ?></h3>
                                    <p><?php echo $this->escape($service['description']); ?></p>
                                </figcaption>
                            </figure>
                        </article>
                    </div>
<?php }
?>
            </div>
        </div>
    </section>

    <section class="portfolio">
        <div class="container">
            <h3 class="text-center">Check Out Our Products In Photo Galleries <br><?php if ($this->photoGalleriesPages) { ?>
                    <small><a href="<?php echo $this->sitemapPageUrl($this->photoGalleriesPages['id']); ?>">View all</a></small>
                <?php } ?></h3>
            <div class="row equal">
                <?php
                foreach ($photoGalleries as $photoGallery) {
                    ?>
                    <div class="col-xs-12 col-md-6 col-lg-4">

                        <figure class="figure center-block">
                            <img src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>"   class="img-responsive double" alt="">
                            <a href="<?php echo $this->photoGalleryUrl($photoGallery); ?>"><figcaption class="figure-caption">
                                    <h4><?php echo $this->escape($photoGallery['title']); ?></h4>
                                </figcaption></a>

                        </figure> 
                    </div>
<?php } ?>

            </div>
        </div>
    </section>  


    <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->baseUrl('/CV-Cubes-Bojan-Joncic.pdf'); ?>" target="_blank"> <button class="btn btn-default" type="button">Get Price List</button></a>
            </div>
        </div>
    </section>
    <section class="googleMap">

        <div class="mapWrapper">
            <div id='gmap_canvas' ></div>		  
        </div>

        <div class="formWrapp">

            <div class="formContact">
                <div class="adress">
                    <h2>Contact Us </h2>
                    <h3>011 783 99 99</h3>
                    <p>Gospodara Vucica 33, 11000 Belgrade, Serbia</p>
                </div>
                <form class="form-group">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Name" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Email" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-xs-12">
                            <div class="input-group">
                                <button id="mail-link" class="btn btn-default formBtn" type="button">Contact Us</button>
                            </div><!-- /input-group -->
                        </div>

                    </div><!-- /.row -->
                </form>			    
            </div>
        </div>
    </section>
<!--    <section class="information">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <h3>Catalog</h3>
                    <div class="row">
                        <div class="col-md-4">
                            <p><a href="">Interior</a></p>
                            <p><a href="">Exterior</a></p>
                            <p><a href="">Performance</a></p>
                            <p><a href="">Lighting</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">Wheels & Tires</a></p>
                            <p><a href="">Audio</a></p>
                            <p><a href="">Repair Parts</a></p>
                            <p><a href="">Body Parts</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">RV Parts</a></p>
                            <p><a href="">Tools & Garage</a></p>
                            <p><a href="">Outdoor</a></p>
                        </div>
                    </div>

                </div>
                <div class=" col-md-3">
                    <h3>Delivery Information</h3>
                    <p><a href="">Delivery Information</a></p>
                    <p><a href="">Privacy policy</a></p>
                    <p><a href="">Terms & Condition</a></p>
                    <p><a href="">Contact us</a></p>

                </div>
                <div class=" col-md-3">
                    <h3>Our service</h3>
                    <p><a href="">My Account</a></p>
                    <p><a href="">Returns</a></p>
                    <p><a href="">Site map</a></p>
                </div>
            </div>
        </div>
    </section>-->
</main>
