<?php
$sitemapPage = $this->sitemapPage;
$indexSlides=$this->indexSlides;
$news = $this->news;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<article class="container-fluid slide_carusel">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="6000" data-pause="hover">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php for ($carousel = 0; $carousel < count($this->indexSlides); $carousel++) { ?>
                <li 
                    data-target="#carousel-example-generic" 
                    data-slide-to="<?php echo $carousel; ?>" <?php echo $carousel == 0 ? "class=\"active\"" : ''; ?>>
                </li>
            <?php } ?>
        </ol>

        <!-- Wrapper for slides -->
<div class="carousel-inner" role="listbox">
            <?php $carouselInner=0; foreach ($this->indexSlides as $indexSlide) { ?>
            <div class="item <?php echo $carouselInner == 0 ? "active" : "" ; $carouselInner++;?>">
                <img class="img-responsive" src="<?php echo $this->indexSlideImgUrl($indexSlide);?>" alt="" />
                    
                <div class="carousel-caption">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                    <h2><?php echo $this->escape($indexSlide['title']);?></h2>
                </div>
                <div class="carousel-caption-right">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </div>
            </div>
<?php }?>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

            <span class="sr-only">Next</span>
        </a>
    </div>

</article>
<main>
<!--    <section class="search">
        <div class="container">
            <form method="POST" >
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" placeholder="Type here the name of spare parts, model car or VIN-code">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Find goods</button>
                    </span>
                </div>
            </form>
            <p>For example: <span>Сute cars parts </span> or <span> Cute-cute parts</span></p>
        </div>
    </section>-->
    <section class="container cars">
        <div class="owl-carousel">
            <div class="item">
                <a href="#"><img src="img/bmw_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/citroen.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/fiat_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/honda.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/kia_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/man_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/nissan.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/wv_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/bmw_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/citroen.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/fiat_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/honda.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/kia_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/man_logo.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/nissan.png" alt=""/></a>
            </div>
            <div class="item">
                <a href="#"><img src="img/wv_logo.png" alt=""/></a>
            </div>

        </div>


    </section>
    <section class="container goods">
        <div class="row">
            <div class="col-md-12 buttons">

                <button type="button" class="btn btn-primary down-arrow">Popular</button>
                <button type="button" class="btn items sale">Sale 50%</button>
                <button type="button" class="btn items">New</button>
                <button type="button" class="btn items">Action</button>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items2.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T-Rex®</h3></a>
                            <p>Billet Grilles</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#">
                            <img class="img-responsive" src="img/items1.jpg" alt=""/>
                        </a>
                        <figcaption>
                            <a href="#"><h3>BedRug Bed Mat</h3></a>
                            <p>Bed Accessories</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items3.png" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>KW Suspensions®</h3></a>
                            <p>Suspension Systems </p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items4.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T5i®</h3></a>
                            <p>Spoilers & Wings</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items2.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T-Rex®</h3></a>
                            <p>Billet Grilles</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#">
                            <img class="img-responsive" src="img/items1.jpg" alt=""/>
                        </a>
                        <figcaption>
                            <a href="#"><h3>BedRug Bed Mat</h3></a>
                            <p>Bed Accessories</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items3.png" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>KW Suspensions®</h3></a>
                            <p>Suspension Systems </p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items4.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T5i®</h3></a>
                            <p>Spoilers & Wings</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items2.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T-Rex®</h3></a>
                            <p>Billet Grilles</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#">
                            <img class="img-responsive" src="img/items1.jpg" alt=""/>
                        </a>
                        <figcaption>
                            <a href="#"><h3>BedRug Bed Mat</h3></a>
                            <p>Bed Accessories</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items3.png" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>KW Suspensions®</h3></a>
                            <p>Suspension Systems </p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <article class="items center-block">

                    <figure>
                        <a href="#"><img class="img-responsive" src="img/items4.jpg" alt=""/></a>
                        <figcaption>
                            <a href="#"> <h3>T5i®</h3></a>
                            <p>Spoilers & Wings</p>
                            <button type="button" class="btn">$54<sup>99</sup></button>
                        </figcaption>

                    </figure>
                </article>
            </div>
            <div class="col-xs-12 showMore">
                <a href="#"><span class="glyphicon glyphicon-chevron-down"></span>Show 12 more goods</a>
            </div>
        </div>

    </section>
    <section class="soldParts">
        <div class="transparentColor">
            <div class="container">
                <div  class="row">
                    <article class="col-xs-6 col-md-3 text-center">
                        <h3>2580</h3>
                        <p>Gear boxes</p>
                    </article>
                    <article class="col-xs-6 col-md-3 text-center">
                        <h3>1820</h3>
                        <p>Tuning goods</p>
                    </article>
                    <article class="col-xs-6 col-md-3 text-center">
                        <h3>4582</h3>
                        <p>Oil and supplies</p>
                    </article>
                    <article class="col-xs-6 col-md-3 text-center">
                        <h3>2524</h3>
                        <p>Devices</p>
                    </article>
                </div>
            </div>
        </div>
    </section>
    <section class="news">
        <div class="container">
            <h3 class="text-center">NEWS <br><?php if ($this->newsSitemapPage) {?>
		<small><a href="<?php echo $this->sitemapPageUrl($this->newsSitemapPage['id']);?>">View all</a></small>
                <?php }?></h3>
            
            <div class="row">
                <div class="col-xs-10">
                    <div class="slider"><!-- The slider -->
                        <div><!-- A mandatory div used by the slider -->
                            <!-- Each div below is considered a slide -->
                            <?php foreach ($news as $oneNews) {
                    ?>
                            <div>
                                <figure class="newsItem">
                                    <div class="imgNews">
                                        <img class="img-responsive" src="<?php echo $this->newsImgUrl($oneNews); ?>" alt=""/>
                                        <div class="hoverNews text-center">
                                            <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                            <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                            <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                        </div>
                                    </div>

                                    <figcaption>
                                        <a href="#"><h4><?php echo $this->escape($oneNews['title']); ?></h4></a>
                                        <button type="button" class="btn items"><?php echo $this->escape($oneNews['date']); ?></button>
                                        <button type="button" class="btn items">Read More</button>
                                        <p><?php echo $this->escape($oneNews['description']); ?></p>

                                    </figcaption>
                                </figure>
                            </div>
                            <?php }
                        ?>
                        </div>

                    </div>
                </div>
                <div class="col-xs-2 controlsNews">

                    <span id="go-left" class="glyphicon glyphicon-menu-left"></span>
                    <span id="go-right" class="glyphicon glyphicon-menu-right"></span>



                </div>

            </div>
        </div>
    </section>
    <section class="cuteParts">
        <div class="transparentColor">
            <div class="container">
                <div  class="row">
                    <article class="tuningCenter col-md-6">
                        <h4><img src="img/logo_dark.png" alt=""/>Cute parts</h4>
                        <h3>Tuning Center</h3>
                        <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, 
                            quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia,
                            malis necessitatibus no mei.  Volumus sensibus qui ex, eum duis doming ad. </p>

                    </article>
                </div>
            </div>
            <div class="pumpRide text-center"><h3>Pump your ride with our services</h3></div>
        </div>
    </section>
    <section class="pumpOptions">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <article class="part center-block">

                        <figure>
                            <img class="center-block" src="img/devices_icon.png" alt=""/>
                            <figcaption class="text-center">
                                <a href="#"><h3>Devices</h3></a>
                                <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney 
                                    College in Virginia, looked up one of the more obscure Latin words.</p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-3">
                    <article class="part center-block">

                        <figure>
                            <img class="center-block" src="img/chip_icon.png" alt=""/>
                            <figcaption class="text-center">
                                <a href="#"><h3>Devices</h3></a>
                                <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney 
                                    College in Virginia, looked up one of the more obscure Latin words.</p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-3">
                    <article class="part center-block">

                        <figure>
                            <img class="center-block" src="img/sock_icon.png" alt=""/>
                            <figcaption class="text-center">
                                <a href="#"><h3>Devices</h3></a>
                                <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney 
                                    College in Virginia, looked up one of the more obscure Latin words.</p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-3">
                    <article class="part center-block">

                        <figure>
                            <img class="center-block" src="img/wheels_icon.png" alt=""/>
                            <figcaption class="text-center">
                                <a href="#"><h3>Devices</h3></a>
                                <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney 
                                    College in Virginia, looked up one of the more obscure Latin words.</p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        </div>
    </section>

    <section class="portfolio">
        <div class="container">
            <div class="row equal">
                <div class="col-xs-12 col-md-5 col-lg-5">
                    <figure class="figure center-block">
                        <img src="img/portfolioItem.jpg"   class="img-responsive double" alt="A generic square placeholder image with rounded corners in a figure.">
                        <figcaption class="figure-caption">
                            <a href="#"><h4>New Tuning Packge for Range Rover Sport</h4></a>
                            <a href="#"><p>24 comments</p></a>
                        </figcaption>
                    </figure> 
                </div>
                <div class="col-xs-12 col-md-5 col-lg-5">
                    <div class="row">
                        <div class=" col-sm-12">
                            <figure class="figure center-block">
                                <img src="img/portfolioItem1.jpg"   class="img-responsive" alt="A generic square placeholder image with rounded corners in a figure.">
                                <figcaption class="figure-caption">
                                    <a href="#"><h4>New Tuning Packge for Range Rover Sport</h4></a>
                                    <a href="#"><p>24 comments</p></a>
                                </figcaption>
                            </figure> 
                        </div>
                    </div>
                    <div class="row">
                        <div class=" col-sm-6">
                            <figure class="figure center-block">
                                <img src="img/porfolioItem2.jpg"   class="img-responsive" alt="A generic square placeholder image with rounded corners in a figure.">
                                <figcaption class="figure-caption">
                                    <a href="#"><h4>New Tuning Packge for Range Rover Sport</h4></a>
                                    <a href="#"><p>24 comments</p></a>
                                </figcaption>
                            </figure> 
                        </div>
                        <div class="col-sm-6">
                            <figure class="figure center-block">
                                <img src="img/porfolioItem2.jpg"    class="img-responsive" alt="A generic square placeholder image with rounded corners in a figure.">
                                <figcaption class="figure-caption">
                                    <a href="#"><h4>New Tuning Packge for Range Rover Sport</h4></a>
                                    <a href="#"><p>24 comments</p></a>
                                </figcaption>
                            </figure> 
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-2 col-lg-2 cen">
                    <figure class="figure center-block">
                        <img src="img/porfolioItem3.jpg"    class="img-responsive double" alt="A generic square placeholder image with rounded corners in a figure.">
                        <figcaption class="figure-caption">
                            <a href="#"><h4>New Tuning Packge for Range Rover Sport</h4></a>
                            <a href="#"><p>24 comments</p></a>
                        </figcaption>
                    </figure> 
                </div>  
            </div>
        </div>
    </section>  


    <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <button class="btn btn-default" type="button">Get Price</button>
            </div>
        </div>
    </section>
    <section class="googleMap">

        <div class="mapWrapper">
            <div id='gmap_canvas' ></div>		  
        </div>

        <div class="formWrapp">

            <div class="formContact">
                <div class="adress">
                    <h2>Contact Us</h2>
                    <h3>1-800-987-0654 321</h3>
                    <p>SUNSET BLVD., BEVERLY HILLS, CA 90210</p>
                </div>
                <form class="form-group">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Name" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Email" aria-label="...">
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-xs-12">
                            <div class="input-group">
                                <button class="btn btn-default formBtn" type="submit">Contact Us</button>
                            </div><!-- /input-group -->
                        </div>

                    </div><!-- /.row -->
                </form>			    
            </div>
        </div>
    </section>
    <section class="information">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <h3>Catalog</h3>
                    <div class="row">
                        <div class="col-md-4">
                            <p><a href="">Interior</a></p>
                            <p><a href="">Exterior</a></p>
                            <p><a href="">Performance</a></p>
                            <p><a href="">Lighting</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">Wheels & Tires</a></p>
                            <p><a href="">Audio</a></p>
                            <p><a href="">Repair Parts</a></p>
                            <p><a href="">Body Parts</a></p>
                        </div>
                        <div class="col-md-4">
                            <p><a href="">RV Parts</a></p>
                            <p><a href="">Tools & Garage</a></p>
                            <p><a href="">Outdoor</a></p>
                        </div>
                    </div>

                </div>
                <div class=" col-md-3">
                    <h3>Delivery Information</h3>
                    <p><a href="">Delivery Information</a></p>
                    <p><a href="">Privacy policy</a></p>
                    <p><a href="">Terms & Condition</a></p>
                    <p><a href="">Contact us</a></p>

                </div>
                <div class=" col-md-3">
                    <h3>Our service</h3>
                    <p><a href="">My Account</a></p>
                    <p><a href="">Returns</a></p>
                    <p><a href="">Site map</a></p>
                </div>
            </div>
        </div>
    </section>
</main>