<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>

            <div class="container">
                <article>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                        <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                            <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                        <?php } ?>
                    </ol>
                </article>
            </div>       
        <main>
            <section class="news newsPage">
                <div class="container">
                    <h3>NEWS</h3>
                    <div class="row">


                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>

                                <figcaption>
                                    <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                        Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                        Volumus sensibus qui ex, eum duis doming ad.</p>

                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car1.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>
                                <figcaption>
                                    <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                        Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                        Volumus sensibus qui ex, eum duis doming ad.</p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car1.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>
                                <figcaption>
                                    <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                        Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                        Volumus sensibus qui ex, eum duis doming ad.</p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>
                                <figcaption>
                                   <a href="#"> <h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                        Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                        Volumus sensibus qui ex, eum duis doming ad.</p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car1.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>
                                <figcaption>
                                   <a href="#"> <h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                        Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                        Volumus sensibus qui ex, eum duis doming ad.</p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <figure class="newsItem">
                                <div class="imgNews">
                                    <img class="img-responsive" src="img/news_car.jpg" alt=""/>
                                    <div class="hoverNews text-center">
                                        <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                        <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                    </div>
                                </div>
                                <figcaption>
                                    <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                                    <button type="button" class="btn items">25 April 2015</button>
                                    <button type="button" class="btn items">Add comment</button>
                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem</p>
                                </figcaption>
                            </figure>
                        </div>


                    </div>
                </div>
            </section>
            <section class="getPrice">
                <div class="container">
                    <div class="col-md-10 text-center">
                        <h2>You want to know what else can our team? Well, download and see</h2>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-default" type="button">Get Price</button>
                    </div>
                </div>
            </section>


            <section class="information">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-md-6">
                            <h3>Catalog</h3>
                            <div class="row">
                                <div class="col-md-4">
                                    <p><a href="">Interior</a></p>
                                    <p><a href="">Exterior</a></p>
                                    <p><a href="">Performance</a></p>
                                    <p><a href="">Lighting</a></p>
                                </div>
                                <div class="col-md-4">
                                    <p><a href="">Wheels & Tires</a></p>
                                    <p><a href="">Audio</a></p>
                                    <p><a href="">Repair Parts</a></p>
                                    <p><a href="">Body Parts</a></p>
                                </div>
                                <div class="col-md-4">
                                    <p><a href="">RV Parts</a></p>
                                    <p><a href="">Tools & Garage</a></p>
                                    <p><a href="">Outdoor</a></p>
                                </div>
                            </div>

                        </div>
                        <div class=" col-md-3">
                            <h3>Delivery Information</h3>
                            <p><a href="">Delivery Information</a></p>
                            <p><a href="">Privacy policy</a></p>
                            <p><a href="">Terms & Condition</a></p>
                            <p><a href="">Contact us</a></p>

                        </div>
                        <div class=" col-md-3">
                            <h3>Our service</h3>
                            <p><a href="">My Account</a></p>
                            <p><a href="">Returns</a></p>
                            <p><a href="">Site map</a></p>
                        </div>
                    </div>
                </div>
            </section>

        </main>

