 <?php
$sitemapPage = $this->sitemapPage;
$news = $this->news;
$item = $this->item;
$sitemapPageBreadcrumbs = $this->breadcrumb;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<section class="bredcrumbs">

    <div class="container">
        <article>
            <ol class="breadcrumb">
                        <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                        <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                            <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                        <?php } ?>
                    </ol>
        </article>
    </div>

</section>


<main class="newsItem">

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-uppercase"><?php echo $this->escape($item['title']); ?></h3>
                </div>
                <div class="col-xs-6 col-md-4">
                    <figure>
                        <img class="img-responsive" src="<?php echo $this->newsImgUrl($item); ?>" alt=""/>
                    </figure>
                </div>
                <div class="col-xs-6 col-md-4">
                    <p><?php echo $this->escape($item['description']); ?></p>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <button type="button" class="btn items date">Aded:<?php echo $this->escape($item['date']); ?></button>
                </div>
<!--                <div class="col-xs-6 text-right">
                    <p>Tags: <a href="#"> Aenean  </a> <a href="#"> Vulputate</a> <a href="#"> Aenean</a></p>
                </div>-->
            </div>
<!--            <div class="row addComment">
                <div class="col-md-3">
                    <h4 class="text-uppercase">Add Comment</h4>

                    <form method="POST">
                        <div class="form-group">
                            <label class="sr-only" for="name">Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label class="sr-only"  for="reviw">Review</label>
                            <textarea  id="reviw" rows="6" placeholder="Message"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Add comment</button>
                    </form>
                </div>

                <div class="col-md-9 review">
                    <h4 class="text-uppercase">Review</h4>
                    <div>
                        <div class="media">
                            <ul class="media-list">


                                <li class="media">
                                    <a class="pull-left" href="#">
                                        <figure>
                                            <img class="media-object img-circle"   src="http://placehold.it/80x80" alt="" />
                                        </figure>
                                    </a>
                                    <div class="media-body"><div>
                                            <h3 class="media-heading">Jane</h3>
                                            <p><span class="mediaDate">25 April 2015  20:09</span></p><br>


                                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                                Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa.
                                                Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec
                                                quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                                                Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
                                            <div class="row">
                                                <div class="col-xs-7">
                                                    <a href="$">Replay </a>|
                                                    <a href="$">Repost </a>
                                                </div>
                                                <div class="col-xs-5 text-right">
                                                    <a href="$">Hide</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="media">
                                            <a class="pull-left" href="#">
                                                <img class="media-object img-circle"   src="http://placehold.it/80x80" alt="" />
                                            </a>
                                            <div class="media-body">
                                                <h3 class="media-heading">Kevin Linds</h3>
                                                <p><span class="mediaDate">25 April 2015  20:09</span></p><br>
                                                <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                                    Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa.
                                                    Cum sociis natoque penatibus et magnis dis parturient montes, nascetur  </p>
                                                <div class="row">
                                                    <div class="col-xs-7">
                                                        <a href="$">Replay </a>|
                                                        <a href="$">Repost </a>
                                                    </div>
                                                    <div class="col-xs-5 text-right">
                                                        <a href="$">Hide</a>
                                                    </div>
                                                </div>
                                                <div class="media">
                                                    <a class="pull-left" href="#">
                                                        <img class="media-object img-circle"   src="http://placehold.it/80x80" alt="" />
                                                    </a>

                                                    <div class="media-body">
                                                        <h3 class="media-heading"><span class="jobTitle text-uppercase">Engineer</span>Sergio Pinson</h3>
                                                        <p><span class="mediaDate">25 April 2015  20:09</span></p><br>
                                                        <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                                            Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa.
                                                            Cum sociis natoque penatibus et magnis dis parturient montes, nascetur  </p>
                                                        <div class="row">
                                                            <div class="col-xs-7">
                                                                <a href="$">Replay </a>|
                                                                <a href="$">Repost </a>
                                                            </div>
                                                            <div class="col-xs-5 text-right">
                                                                <a href="$">Hide</a>
                                                            </div>
                                                        </div>
                                                         Nested media object 

                                                    </div>
                                                </div>
                                                 Nested media object 
                                                <div class="media">
                                                    <a class="pull-left" href="#">
                                                        <img class="media-object img-circle"   src="http://placehold.it/80x80" alt="" />
                                                    </a>
                                                    <div class="media-body">
                                                        <h3 class="media-heading">Lili Mc Laud</h3>
                                                        <p><span class="mediaDate">25 April 2015  20:09</span></p><br>
                                                        <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.</p>
                                                        <div class="row">
                                                            <div class="col-xs-7">
                                                                <a href="#">Replay </a>|
                                                                <a href="#">Repost </a>
                                                            </div>
                                                            <div class="col-xs-5 text-right">
                                                                <a href="#">Hide</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </li>
                                <li class="media">
                                    <a class="pull-left" href="#">
                                        <figure>
                                            <img class="media-object img-circle"   src="http://placehold.it/80x80" alt="" />
                                        </figure>
                                    </a>
                                    <div class="media-body"><div>
                                            <h3 class="media-heading">Janson</h3>
                                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                                Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa.
                                                Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec
                                                quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                                                Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
                                            <div class="row">
                                                <div class="col-xs-7">
                                                    <a href="#">Replay </a>|
                                                    <a href="#">Repost </a>
                                                </div>
                                                <div class="col-xs-5 text-right">
                                                    <a href="#">Hide</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>-->
        </div>
    </section>
    <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->baseUrl('/CV-Cubes-Bojan-Joncic.pdf');?>" target="_blank"> <button class="btn btn-default" type="button">Get Price List</button></a>
            </div>
        </div>
    </section>
</main>
