<?php
$sitemapPage=$this->sitemapPage;
$photoGalleries = $this->photoGalleries;
$this->headTitle($this->sitemapPage['title']);
$this->headMeta()->appendName('description', $this->sitemapPage['description']);
?>
<main>
    <div class="container">

        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
        
        <div id="content">
			<div class="">
				<ul class="thumbnails row block projects" id="quicksand">
                                    <?php foreach ($photoGalleries as $photoGallery) { ?>
					<li class="col-md-4" data-id="1" data-type="print">
						<div class="">
							<div class="project">
								<a class="lnk-polaroid" href="<?php echo $this->photoGalleryUrl($photoGallery); ?>">
									<img src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>" alt="<?php echo $this->escape($photoGallery['title']); ?>" class="img-polaroid img-responsive" />
								</a>
								<h4 class="title">
									<a href="<?php echo $this->photoGalleryUrl($photoGallery); ?>"><?php echo $this->escape($photoGallery['title']); ?></a>
								</h4>
								<p class="muted"><?php echo $this->escape($photoGallery['description']); ?></p>
							</div>
						</div>
					</li>
                                     <?php } ?>       
				</ul>
			</div>
		</div>
    </div>
</main>


		