<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?php echo $this->headTitle('Auto Parts web-shop')->setSeparator(' | '); ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- @todo: fill with your company info or remove -->
        <?php echo $this->headMeta(); ?>
        <!-- General CSS -->

        <?php echo $this->headLink(); ?>
        <!-- Theme  CSS -->

        <?php echo $this->headStyle(); ?>
<a href=>
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/apple-touch-icon.png'); ?>">
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <script src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyD5UMz1q-VLI2igjQT7a8_ADtDuRBxMMRQ'></script>
        <link href="<?php echo $this->baseUrl('/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/bootstrap.min.css'); ?>">
        <link href="<?php echo $this->baseUrl('/css/owl.carousel.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/css/starrr.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/css/jquery.nstSlider.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/main.css'); ?>">
        <link href="<?php echo $this->baseUrl('/css/responsive.css'); ?>" rel="stylesheet" type="text/css"/>
        <script src="<?php echo $this->baseUrl('/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'); ?>"></script>
        <?php echo $this->headScript(); ?>
    </head>

    <!-- ======== @Region: body ======== -->
    <body>
        <header>
           
            <section  class="navigation">
                <div class="container">
                    <article class="navigation-bar">
                        <nav class="navbar navbar-inverse">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span> 
                                </button>
                                <a class="navbar-brand" href="#"><img src="/img/logo_icon.png" alt=""/>Gear</a>
                            </div>
                            <div class="collapse navbar-collapse" id="myNavbar">                              
                                <?php echo $this->topMenuHtml();?>
                                <ul class="nav navbar-nav navbar-right">

                                    <li><a href="#" id="shopingCart"><img src="/img/cart_icon.png" alt=""/> Inbox <span class="badge">42</span></a></li>
                                </ul>
                            </div>
                        </nav>
                    </article>
                </div>
            </section>
        </header>
        <div class="shopingcart">
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <article class="">
                                <figure>
                                    <a href="#"><img class="img-responsive" src='http://placehold.it/100x100' alt=""></a>
                                </figure>
                                <div class="">
                                    <p class=""><a href="">Lorem ipsum</a></p>

                                </div>
                            </article>
                        </td>
                        <td>2835 DIN</td>
                        <td><a href="#" class="closeShop">X</a></td>
                    </tr>
                    <tr>
                        <td>
                            <article class="clearfix">
                                <figure>
                                    <a href="#"><img class="img-responsive" src='http://placehold.it/100x100' alt=""></a>
                                </figure>
                                <div class="historyProduct">
                                    <p class=""><a href="#">Lorem ipsum</a></p>
                                </div>
                            </article>
                        </td>
                        <td>2835 DIN</td>
                        <td><a href="#" class="closeShop">X</a></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>TOTAL: <span class="">5670 din</span></td>
                        <td colspan="2">
                            <a href="#l" class="btn btn-default" id="buy" >Buy</a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <?php echo $this->layout()->content; ?>
        <footer>
            <div class="container">
                <article class="navigation-bar">
                    <nav class="navbar navbar-inverse">
                        <div>
                                <?php echo $this->topMenuHtml();?>
                            <ul class="nav navbar-nav navbar-right socialNetwork">
                                <li>
                                    <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </article>
            </div>
            <section class="payments">
                <div class="container">
                    <div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="">
                                    <img src="/img/payPal.png" alt=""/>
                                </a> 
                                <a href="">
                                    <img src="/img/masterCard.png" alt=""/>
                                </a>
                                <a href="">
                                    <img src="/img/visa_icon.png" alt=""/>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="">Gear © 2016 All Rights Reserved</a>
                            </li>  
                        </ul>
                    </div>
                </div>
            </section>
            <section class="development ">
                <p class="text-center">Ovaj projekat je realizovan u okviru <a href="school.cubes.rs">CUBES SCHOOL</a>. Projekat realizovali: FRONTEND <a href="#">Ivan Trickovic</a>, BACKEND </p>
            </section>
        </footer>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a porttitor lectus. Quisque vitae bibendum mi,
                            eu malesuada lacus. Praesent placerat sodales massa, non sodales odio iaculis ac. Cras volutpat, justo vitae fringilla tincidunt,
                            nunc dolor vehicula nisl, ac aliquet tortor tellus vel ante. Maecenas euismod, ante in dictum gravida, magna leo porttitor sem,
                            eu posuere lorem ligula quis turpis. Nam eget aliquam erat, vel ornare odio. Curabitur vitae lorem volutpat, 
                            tristique augue eget, tincidunt lacus. Praesent in odio lorem. </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <!--Scripts -->
        <?php echo $this->inlineScript(); ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/js/vendor/jquery-1.11.2.js'); ?>"><\/script>');</script>

        <script src="<?php echo $this->baseUrl('/js/vendor/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/owl.carousel.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('/js/jquery.diyslider.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('/js/jquery.nstSlider.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('/js/jquery.validation.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('/js/starrr.js" type="text/javascript'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/main.js'); ?>"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function (b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function () {
                            (b[l].q = b[l].q || []).push(arguments);
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r);
            }(window, document, 'script', 'ga'));
            ga('create', 'UA-XXXXX-X', 'auto');
            ga('send', 'pageview');

        </script>
    </body>

</html>
