<?php
$products = $this->products;
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<div class="container">
    <article>
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
            <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
            <?php } ?>
        </ol>
    </article>
</div>
<main>
    <section class="search">
        <div class="container">
            <form method="POST" >
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" placeholder="Type here the name of spare parts, model car or VIN-code">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Find goods</button>
                    </span>
                </div>
            </form>
            <p>For example: <span>Сute cars parts </span> or <span> Cute-cute parts</span></p>
        </div>
    </section>

    <section class="container goods borderGoods">

        <div class="row">
            <div class="col-md-2">
                <article class="row">
                    <div class="col-xs-12">
                        <aside class="options">
                            <h2>Options<span class="glyphicon glyphicon-menu-down"></span></h2>
                            <div class="showOption">
                                <article class="catalog">
                                    <h2>Catalog</h2>
                                    <div class="category">
                                        <h3>Categoty name <span>x</span></h3>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4 class="active">Sub-categoty  <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                    </div>
                                </article>
                                <article class="type">
                                    <h2>Type</h2>
                                    <form role="form">
                                        <div class="form-group">
                                            <select class="form-control" id="sel1">
                                                <option value="" disabled selected>Select type</option>
                                                <option value="">1</option>
                                                <option value="">2</option>
                                                <option value="">3</option>
                                                <option value="">4</option>
                                            </select>
                                        </div>
                                    </form>
                                </article>
                                <article class="radioButtons">
                                    <h2>Radio buttons</h2>
                                    <form role="form">
                                        <div class="radio">
                                            <label><input type="radio" name="optradio">Hard</label>
                                        </div>
                                        <div class="radio">
                                            <label><input type="radio" name="optradio">Soft</label>
                                        </div>

                                    </form>
                                </article>
                                <article class="color">
                                    <h2>Color</h2>
                                    <h4><span class="lemon"></span> Lemon yellow</h4>
                                    <h4><span class="pink"></span> Pink kitty</h4>
                                </article>
                                <article class="checkboxGroup">
                                    <h2>Checkbox</h2>
                                    <form role="form">
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Regular</label>
                                        </div>
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Tuning</label>
                                        </div>
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Exclusive</label>
                                        </div>

                                    </form>
                                </article>
                                <article class="rangeSlider clearfix">
                                    <h2>Range</h2>
                                    <div class="nstSlider" data-range_min="0" data-range_max="800" 
                                         data-cur_min="50"  data-cur_max="524">

                                        <div class="bar"></div>
                                        <div class="leftGrip"></div>
                                        <div class="rightGrip"></div>
                                    </div>
                                    <div class="leftLabel pull-left"></div>
                                    <div class="rightLabel pull-right"></div>
                                </article>
                            </div>
                        </aside>
                    </div>
                </article>
            </div>
            
            <div class="col-md-10">
                <?php foreach ($products as $product) {
                    ?>
                    <div class="col-sm-6 col-md-4 col-lg-3">

                        <article class="items center-block">

                            <figure>
                                <a href="<?php echo $this->productItemUrl($product); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/></a>
                                <figcaption>
                                    <a href="<?php echo $this->productItemUrl($product); ?>"> <h3><?php echo $this->escape($product['type']); ?></h3></a>
                                    <p><?php echo $this->escape($product['model']); ?></p>
                                    <button type="button" class="btn"><?php echo $this->escape($product['price']); ?></button>
                                </figcaption>

                            </figure>
                        </article>

                    </div>
                <?php }
                ?>
                <div class="col-xs-12 showMore"></div>
            </div>
        </div>
    </section>

    <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->baseUrl('/CV-Cubes-Bojan-Joncic.pdf'); ?>" target="_blank"> <button class="btn btn-default" type="button">Get Price List</button></a>
            </div>
        </div>
    </section>

    <div class="container">
        <!-- Filter Controls - Simple Mode -->
<!--        <div class="row text-center">  
             A basic setup of simple mode filter controls, all you have to do is use data-filter="all"
            for an unfiltered gallery and then the values of your categories to filter between them 
            <ul class="simplefilter list-unstyled list-inline pull-left">

                <li class="active" data-filter="all">ALL</li>
                <li data-filter="1">ACTION</li>
                <li data-filter="2">NEW</li>
                <li data-filter="3">BERRIES</li>                        
            </ul>
        </div>-->



<!--        <div class="row">
             This is the set up of a basic gallery, your items must have the categories they belong to in a data-category
            attribute, which starts from the value 1 and goes up from there 
            <div class="filtr-container">
                <section class="goods">
                    <div class="col-sm-6 col-md-4 col-lg-3 filtr-item" data-category="1" data-sort="FRUITS">
                        <article class="items center-block">

                            <figure>
                                <a href="#"><img class="img-responsive" src="img/items3.png" alt=""/></a>
                                <figcaption>
                                    <a href="#"> <h3>KW Suspensions®</h3></a>
                                    <p>Suspension Systems </p>
                                    <button type="button" class="btn">$54<sup>99</sup></button>
                                </figcaption>

                            </figure>
                        </article>
                    </div>
                </section>
                <div class="col-xs-6 col-sm-4 col-md-4 filtr-item" data-category="2" data-sort="VEGETABLES">
                    <a href="#"><img class="img-responsive" src="img/items2.jpg" alt="sample image"></a>

                </div>
                <div class="col-xs-6 col-sm-4 col-md-4 filtr-item" data-category="3" data-sort="BERRIES">
                    <a href="#"><img class="img-responsive" src="img/items2.jpg" alt="sample image"></a>

                </div>
                <div class="col-xs-6 col-sm-4 col-md-4 filtr-item" data-category="1" data-sort="FRUITS">
                    <a href="#"><img class="img-responsive" src="img/items4.jpg" alt="sample image"></a>

                </div>

            </div>
        </div>-->



    </div>
</main>

