 <?php
$sitemapPage = $this->sitemapPage;
$products = $this->products;
$productItem = $this->productItem;
$sitemapPageBreadcrumbs = $this->breadcrumb;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<section class="bredcrumbs">
    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
    </div>
</section>
<!--   BREDACRUMBS SECTION START       -->
<!--   MAIN SECTION START       -->
<main class="product">
<!--    <section class="search">
        <div class="container">
            <form method="POST">
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" placeholder="Type here the name of spare parts, model car or VIN-code">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Find goods</button>
                    </span>
                </div>
            </form>
            <p>For example: <span>Сute cars parts </span> or <span> Cute-cute parts</span></p>
        </div>
    </section>-->

    <section class="productInfo">
        <div class="container">
            <div class="row gallery">
                <div class="col-md-9">
                    <h3 class="text-uppercase"><?php echo $this->escape($productItem['type']); ?></h3>
                </div>
                                <div class="col-md-5 col-sm-12 productRate starrr">
                    
                                <ul class="hide-bullets clearfix">
                                    <li class="col-xs-4">
                                        <p>
                                            <img class="img-responsive" src="<?php echo $this->productImgUrl($productItem); ?>" alt=""/>
                                        </p>
                                    </li>
                                    </ul>
                                    <div class="description">
                        <h4 class="text-uppercase">Description</h4>
                        <p><?php echo $this->escape($productItem['description']); ?></p>
                    </div>
                    <div class="technicalCharacteristics">
                        <h4 class="text-uppercase">Technical characteristics</h4>
                        <div class="row">
                            <div class="col-xs-3">
                                <p>Material</p>
                            </div>
                            <div class="col-xs-9">
                                <p>Plastic, Steel, Aluminum, Glass</p>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-3">
                                <p>Width</p>
                            </div>
                            <div class="col-xs-9">
                                <p>150mm</p>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-3">
                                <p>Height</p>
                            </div>
                            <div class="col-xs-9">
                                <p>40mm</p>
                            </div>
                        </div>
                    </div>
                                    <div class="model">
                        <h4 class="text-uppercase">Compatible models </h4>
                        <h5><p><?php echo $this->escape($productItem['model']); ?></p></h5>
                        
                    </div>
<!--                    <div class="productColor">
                        <h4 class="text-uppercase">Color </h4>
                        <div class="row">
                            <div class="col-xs-4">
                                <p class="flex-center"><span></span> Pink kitty</p>
                            </div>
                            <div class="col-xs-4">
                                <p class="flex-center"><span></span> Noble silver</p>
                            </div>
                            <div class="col-xs-4">
                                <p class="flex-center"><span></span> Deep black</p>
                            </div>
                        </div>
                    </div>-->
                    <div class="productType">
<!--                        <h4 class="text-uppercase">Type </h4>
                        <button class="btn btn-default" type="button">Halogen</button>
                        <button class="btn btn-default" type="button">Biksenon</button>
                        <button class="btn btn-default" type="button">LED</button>-->
                        <h4 class="text-uppercase">Price </h4>
                        <div>
                            <h2><?php echo $this->escape($productItem['price']); ?> </h2>
                            <button class="btn btn-primary">Buy now</button>
                        </div>
                    </div>
                    
                    
                </div>
                

                    <div id="main_area" class="center-block">
<!--                         Slider -->
                        <div class="row">

<!--                            <div class="col-sm-12">
                                <div class="col-xs-12" id="slider">
                                     Top part of the slider 
                                    <div class="row">
                                        <div class="col-sm-12" id="carousel-bounding-box">
                                            <div class="carousel slide" id="myCarousel">
                                                 Carousel items 
                                                <div class="carousel-inner">
                                                    
                                                    <div class="item">
                                                        
                                                        <img class="img-responsive" src="" alt=""/>
                                                    </div>

                                                   
                                                </div>
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                                /Slider
                            </div>-->
<div class="col-md-9">
                            <div class="col-md-12" id="slider-thumbs">
                                 
                                
                                <h4 class="text-uppercase">Other products</h4>
                                
                                <ul class="hide-bullets clearfix">
                                 <?php foreach ($products as $product) { ?>   
                                    <li class="col-xs-3">
                                        <a class="thumbnail" id="carousel-selector-1" href="<?php echo $this->productItemUrl($product); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/>
                                        
                                        </a>
                                 <p><?php echo $this->escape($product['model'] . ' '. $product['type']); ?></p>
                                    </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
<!--            <div class="row rateProduct">
                <div class="col-md-3">
                    <h4 class="text-uppercase">Add Review</h4>
                    <p>Rate product</p>
                    <div class='starrr pull-right' id='star1'></div>
                    <form method="POST">
                        <div class="form-group clearfix">
                            <label class="sr-only" for="name">Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="email">Email</label>
                            <input type="email" class="form-control" id="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="good">What Good</label>
                            <textarea id="good" placeholder="What good"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="bad">Good</label>
                            <textarea id="bad" placeholder="What bad"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="reviw">Review</label>
                            <textarea id="reviw" placeholder="Review"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Add review</button>
                    </form>
                </div>
                <div class="col-md-9 review">
                    <h4 class="text-uppercase">Review</h4>
                    <div>
                        <div class="media">
                            <ul class="media-list">
                                <li class="media">
                                    <a class="pull-left" href="#">
                                        <figure>
                                            <img class="media-object img-circle" src="http://placehold.it/80x80" alt="" />
                                        </figure>
                                    </a>
                                    <div class="media-body">
                                        <div>
                                            <h3 class="media-heading">Jane</h3>
                                            <p><span class="mediaDate">25 April 2015  20:09</span></p>
                                            <br>
                                            <h5>Rating:</h5>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog" href="#"></a>
                                            <a class="fa fa-cog" href="#"></a>
                                            <div class="row">
                                                <div class="col-xs-1">
                                                    <h5>Good:</h5>
                                                </div>
                                                <div class="col-xs-10">
                                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-1">
                                                    <h5>Bad:</h5>
                                                </div>
                                                <div class="col-xs-10">
                                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.</p>
                                                </div>
                                            </div>
                                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
                                            <div class="row">
                                                <div class="col-xs-7">
                                                    <a href="$">Replay </a>|
                                                    <a href="$">Repost </a>
                                                </div>
                                                <div class="col-xs-5 text-right">
                                                    <a href="$">Hide</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="media">
                                            <a class="pull-left" href="#">
                                                <img class="media-object img-circle" src="http://placehold.it/80x80" alt="" />
                                            </a>
                                            <div class="media-body">
                                                <h3 class="media-heading">Kevin Linds</h3>
                                                <p><span class="mediaDate">25 April 2015  20:09</span></p>
                                                <br>
                                                <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur </p>
                                                <div class="row">
                                                    <div class="col-xs-7">
                                                        <a href="$">Replay </a>|
                                                        <a href="$">Repost </a>
                                                    </div>
                                                    <div class="col-xs-5 text-right">
                                                        <a href="$">Hide</a>
                                                    </div>
                                                </div>
                                                 Nested media object 
                                                <div class="media">
                                                    <a class="pull-left" href="#">
                                                        <img class="media-object img-circle" src="http://placehold.it/80x80" alt="" />
                                                    </a>
                                                    <div class="media-body">
                                                        <h3 class="media-heading">Lili Mc Laud</h3>
                                                        <p><span class="mediaDate">25 April 2015  20:09</span></p>
                                                        <br>
                                                        <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.</p>
                                                        <div class="row">
                                                            <div class="col-xs-7">
                                                                <a href="#">Replay </a>|
                                                                <a href="#">Repost </a>
                                                            </div>
                                                            <div class="col-xs-5 text-right">
                                                                <a href="#">Hide</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="media">
                                    <a class="pull-left" href="#">
                                        <figure>
                                            <img class="media-object img-circle" src="http://placehold.it/80x80" alt="" />
                                        </figure>
                                    </a>
                                    <div class="media-body">
                                        <div>
                                            <h3 class="media-heading">Janson</h3>
                                            <p><span class="mediaDate">25 April 2015  20:09</span></p>
                                            <br>
                                            <h5>Rating:</h5>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                                            <a class="fa fa-cog" href="#"></a>
                                            <a class="fa fa-cog" href="#"></a>
                                            <div class="row">
                                                <div class="col-xs-1">
                                                    <h5>Good:</h5>
                                                </div>
                                                <div class="col-xs-10">
                                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-1">
                                                    <h5>Bad:</h5>
                                                </div>
                                                <div class="col-xs-10">
                                                    <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.</p>
                                                </div>
                                            </div>
                                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
                                            <div class="row">
                                                <div class="col-xs-7">
                                                    <a href="#">Replay </a>|
                                                    <a href="#">Repost </a>
                                                </div>
                                                <div class="col-xs-5 text-right">
                                                    <a href="#">Hide</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>-->
        </div>
    </section>
<!--    <section class="featuredProducts">
        <div class="container">
            <div class="row">
                <div class="col-md-12 buttons">
                    <button type="button" class="btn btn-primary down-arrow">Popular</button>
                    <button type="button" class="btn items sale">Sale 50%</button>
                    <button type="button" class="btn items">New</button>
                    <button type="button" class="btn items">Action</button>
                </div>
                <div class="row">


                    <div class="col-md-12">

                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T5i®</h3></a>
                                        <p>Spoilers & Wings</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>

                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T-Rex®</h3></a>
                                        <p>Billet Grilles</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Denso® - Alternator</h3></a>
                                        <p>Starters, Alternators, Batteries</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#">  <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Brembo® HR80</h3></a>
                                        <p>Brakes</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Duraflex® - Kit</h3></a>
                                        <p>Body Kits</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>MagnaFlow®</h3></a>
                                        <p>Exhaust Systems</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"> <h3>ZLR Door Kit</h3></a>
                                        <p>Vertical Doors</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Spyder®</h3></a>
                                        <p>Headlights</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>

                        </div>

                    </div>


                </div>
            </div>

    </section>-->
    <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <button class="btn btn-default" type="button">Get Price</button>
            </div>
        </div>
    </section>

</main>
<!--   MAIN SECTION END       -->
<!--   FOOTER SECTION START       -->
