 <?php
$sitemapPage = $this->sitemapPage;
$products = $this->products;
$productItem = $this->productItem;
$sitemapPageBreadcrumbs = $this->breadcrumb;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<main>
<section class="bredcrumbs">
    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li> 
                <?php foreach ($sitemapPageBreadcrumbs as $breadcrumb) { ?>
                    <li><a href=""><?php echo $productItem['type']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
    </div>
</section>

        <section class="productInfo">
            <div class="container">
                <div class="row gallery">
                    <div class="col-xs-12">
                        <h3 class="text-uppercase">Spyder® - Custom Headlights</h3>
                        <p>in <a href="#"> Headlights</a></p>

                    </div>
                    <div class="col-md-7">

                        <div id="main_area" class="center-block">
                            <!-- Slider -->
                            <div class="row">

                                <div class="col-sm-12">
                                    <div class="col-xs-12" id="slider">
                                        <!-- Top part of the slider -->
                                        <div class="row">
                                            <div class="col-sm-12" id="carousel-bounding-box">
                                                <div class="carousel slide" id="myCarousel">
                                                    <!-- Carousel items -->
                                                    <div class="carousel-inner">
                                                        <div class="active item" data-slide-number="0">
                                                           
                                                            <img class="img-responsive" src="<?php echo $this->productImgUrl($productItem); ?>" alt=""/>
                                                        </div>

                                                        <div class="item" data-slide-number="1">
                                                           <img class="img-responsive" src="/img/productGallery1.jpg" alt=""/>
                                                        </div>

                                                        <div class="item" data-slide-number="2">
                                                            <img class="img-responsive" src="/img/productGallery2.jpg" alt=""/>
                                                        </div>

                                                        <div class="item" data-slide-number="3">
                                                            <img class="img-responsive" src="/img/productGallery3.jpg" alt=""/>
                                                        </div>

                                                        <div class="item" data-slide-number="4">
                                                           <img class="img-responsive" src="/img/productGallery4.jpg" alt=""/>
                                                        </div>

                                                        <div class="item" data-slide-number="5">
                                                            <img class="img-responsive" src="/img/productGallery5.jpg" alt=""/>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!--/Slider-->
                                </div>
                                <div class="col-sm-12" id="slider-thumbs">
                                     
                                    <h4 class="text-uppercase">More photos</h4>
                                    <ul class="hide-bullets clearfix">
                                       <?php foreach ($products as $product) { ?>   
                                    <li class="col-xs-3">
                                        <a class="thumbnail" id="carousel-selector-1" href="<?php echo $this->productItemUrl($productItem); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/>
                                        
                                        </a>
                                 <p><?php echo $this->escape($product['model'] . ' '. $product['type']); ?></p>
                                    </li>
                                    <?php } ?>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-5 col-sm-12 productRate starrr">
<!--                        <div>
                            <h4 class="text-uppercase">Product rate</h4>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog" href="#"></a>
                            <a class="fa fa-cog" href="#"></a>
                            <p class="pull-right"><b>4585</b> votes / <b>97</b> last week</p>
                        </div>
                        <div class="productColor">
                            <h4 class="text-uppercase">Color </h4>
                            <div class="row">
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Pink kitty</p>
                                </div>
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Noble silver</p>
                                </div>
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Deep black</p>
                                </div>
                            </div>
                        </div>-->
                        <div class="productType">
                            <h4 class="text-uppercase">Type </h4>
                            <button class="btn btn-default" type="button">Halogen</button>
                            <button class="btn btn-default" type="button">Biksenon</button>
                            <button class="btn btn-default" type="button">LED</button>
                            <h4 class="text-uppercase">Price </h4>
                            <div>
                                <h2>$2849<sup>99</sup> </h2>
                                <button class="btn btn-primary">Buy now</button>
                            </div>
                        </div>
                        <div class="model">
                            <h4 class="text-uppercase">Compatible models </h4>
                            <a href="#">BMW X3</a>,
                            <a href="#">BMW X5</a>
                        </div>
                        <div class="description">
                            <h4 class="text-uppercase">Description</h4>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius. Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. Volumus sensibus qui ex, eum duis doming ad. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p>
                        </div>
                        <div class="technicalCharacteristics">
                            <h4 class="text-uppercase">Technical characteristics</h4>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Material</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>Plastic, Steel, Aluminum, Glass</p>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Width</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>150mm</p>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Height</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>40mm</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </section>
    <div>&nbsp</div>
	<section class="featuredProducts">
	    <div class="container">
		<div class="row">
                    <div class="col-md-12 buttons">
                            <button type="button" class="btn btn-primary down-arrow">Popular</button>
                            <button type="button" class="btn items sale">Sale 50%</button>
                            <button type="button" class="btn items">New</button>
                            <button type="button" class="btn items">Action</button>
                </div>
		    <div class="row">
                    

                    <div class="col-md-12">
                        
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T5i®</h3></a>
                                        <p>Spoilers & Wings</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>

                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T-Rex®</h3></a>
                                        <p>Billet Grilles</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Denso® - Alternator</h3></a>
                                        <p>Starters, Alternators, Batteries</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#">  <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Brembo® HR80</h3></a>
                                        <p>Brakes</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Duraflex® - Kit</h3></a>
                                        <p>Body Kits</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>MagnaFlow®</h3></a>
                                        <p>Exhaust Systems</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                       <a href="#"> <h3>ZLR Door Kit</h3></a>
                                        <p>Vertical Doors</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Spyder®</h3></a>
                                        <p>Headlights</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>

                        </div>
                 
                    </div>


                </div>
	    </div>
	    
	</section>
        <section class="getPrice">
            <div class="container">
                <div class="col-md-10 text-center">
                    <h2>You want to know what else can our team? Well, download and see</h2>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" type="button">Get Price</button>
                </div>
            </div>
        </section>
	
    </main>
    <!--   MAIN SECTION END       -->
    <!--   FOOTER SECTION START       -->
