 <?php
$sitemapPage = $this->sitemapPage;
$products = $this->products;
$productItem = $this->productItem;
$sitemapPageBreadcrumbs = $this->breadcrumb;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<main>
<section class="bredcrumbs">
    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li> 
                <?php foreach ($sitemapPageBreadcrumbs as $breadcrumb) { ?>
                    <li><a href=""><?php echo $productItem['type']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
    </div>
</section>

        <section class="productInfo">
            <div class="container">
                <div class="row gallery">
                    <div class="col-xs-12">
                        <h3 class="text-uppercase"><?php echo $this->escape($productItem['type']); ?></h3>
                        

                    </div>
                    <div class="col-md-7">

                        <div id="main_area" class="center-block">
                            <!-- Slider -->
                            <div class="row">

                                <div class="col-sm-12">

                                    <div class="">
				<ul class="thumbnails row block projects list-unstyled" id="quicksand">
                                    
					<li class="col-md-4" data-id="1" data-type="print">
						<div class="">
							<div class="project">
								<a class="lnk-polaroid" href="">
									<img src="<?php echo $this->productImgUrl($productItem); ?>" alt="<?php echo $this->escape($photoGallery['title']); ?>" class="img-polaroid img-responsive" />
								</a>
								<h4 class="title">
									<a href=""></a>
								</h4>
								<p class="muted"></p>
							</div>
						</div>
					</li>
                                          
				</ul>
			</div>
                                    <!--/Slider-->
                                </div>
                                <div class="col-sm-12" id="slider-thumbs">
                                     
                                    <h4 class="text-uppercase">More Products</h4>
                                    <ul class="hide-bullets clearfix">
                                       <?php foreach ($products as $product) { ?>   
                                    <li class="col-xs-3">
                                        <a class="thumbnail" id="carousel-selector-1" href="<?php echo $this->productItemUrl($product); ?>"><img class="img-responsive" src="<?php echo $this->productImgUrl($product); ?>" alt=""/>
                                        
                                        </a>
                                 <p><?php echo $this->escape($product['model'] . ' '. $product['type']); ?></p>
                                    </li>
                                    <?php } ?>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-5 col-sm-12 productRate starrr">
<!--                        <div>
                            <h4 class="text-uppercase">Product rate</h4>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog fa-cog-yellow" href="#"></a>
                            <a class="fa fa-cog" href="#"></a>
                            <a class="fa fa-cog" href="#"></a>
                            <p class="pull-right"><b>4585</b> votes / <b>97</b> last week</p>
                        </div>
                        <div class="productColor">
                            <h4 class="text-uppercase">Color </h4>
                            <div class="row">
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Pink kitty</p>
                                </div>
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Noble silver</p>
                                </div>
                                <div class="col-xs-4">
                                    <p class="flex-center"><span></span> Deep black</p>
                                </div>
                            </div>
                        </div>-->
                        <div class="productType">
<!--                            <h4 class="text-uppercase">Type </h4>
                            <button class="btn btn-default" type="button"></button>-->
                            
                            <h4 class="text-uppercase">Price </h4>
                            <div>
                                <h2><?php echo $this->escape($productItem['price']); ?> RSD</h2>
                                <button class="btn btn-primary">Buy now</button>
                            </div>
                        </div>
                        <div class="model">
                            <h4 class="text-uppercase">Compatible models </h4>
                            <h2><?php echo $this->escape($productItem['model']); ?></h2>
                        </div>
                        <div class="description">
                            <h4 class="text-uppercase">Description</h4>
                            <p><?php echo $this->escape($productItem['description']); ?> </p>
                        </div>
                        <div class="technicalCharacteristics">
                            <h4 class="text-uppercase">Technical characteristics</h4>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Material</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>Plastic, Steel, Aluminum, Glass</p>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Width</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>150mm</p>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <p>Height</p>
                                </div>
                                <div class="col-xs-9">
                                    <p>40mm</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </section>
    <div>&nbsp</div>
<!--	<section class="featuredProducts">
	    <div class="container">
		<div class="row">
                    <div class="col-md-12 buttons">
                            <button type="button" class="btn btn-primary down-arrow">Popular</button>
                            <button type="button" class="btn items sale">Sale 50%</button>
                            <button type="button" class="btn items">New</button>
                            <button type="button" class="btn items">Action</button>
                </div>
		    <div class="row">
                    

                    <div class="col-md-12">
                        
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T5i®</h3></a>
                                        <p>Spoilers & Wings</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>

                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>T-Rex®</h3></a>
                                        <p>Billet Grilles</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Denso® - Alternator</h3></a>
                                        <p>Starters, Alternators, Batteries</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                    <a href="#">  <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Brembo® HR80</h3></a>
                                        <p>Brakes</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Duraflex® - Kit</h3></a>
                                        <p>Body Kits</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                      <a href="#"><img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>MagnaFlow®</h3></a>
                                        <p>Exhaust Systems</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                       <a href="#"> <h3>ZLR Door Kit</h3></a>
                                        <p>Vertical Doors</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <article class="items center-block">

                                <figure>
                                     <a href="#"> <img class="img-responsive" src="http://placehold.it/350x395" alt=""/></a>
                                    <figcaption>
                                        <a href="#"><h3>Spyder®</h3></a>
                                        <p>Headlights</p>
                                        <button type="button" class="btn">$54<sup>99</sup></button>
                                    </figcaption>

                                </figure>
                            </article>

                        </div>
                 
                    </div>


                </div>
	    </div>
	    
	</section>-->
<!--        <section class="getPrice">
            <div class="container">
                <div class="col-md-10 text-center">
                    <h2>You want to know what else can our team? Well, download and see</h2>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" type="button">Get Price</button>
                </div>
            </div>
        </section>-->
	
    </main>
    <!--   MAIN SECTION END       -->
    <!--   FOOTER SECTION START       -->
