<?php
$this->headTitle('Products - Edit Product');

$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));//za ispis gresaka u formi
?>
<div class="page-header">
    <h1>Products</h1>
    <small>Edit Product</small>
</div>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller'=>'admin_products', 'action'=>'index'), 'default', true) ?>' 
                        class="btn btn-default">
                        <i class="glyphicon glyphicon-arrow-left"></i>Back to all products</a>
                </div>
                
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="update">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Product - <?php echo $this->escape($this->product['model'] . ' ' . $this->product['type']); ?></legend>

                        <!-- Text input-->
<!-- Multiple select-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="supplier_categories">Brand</label>  
                            <div class="col-md-4">
                                <?php
                                    echo $form->getElement('supplier_categories')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'id' => 'supplier_categories',
                                        'required' => 'required'
                                    ));
                                ?>

                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('supplier_categories')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('supplier_categories')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>


                            </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="model">Model</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('model')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter product\'s model',
          'id'=>'model',
          'required'=>'required'
      ));
      ?>
  
  <span class="help-block">min 3 max 10 characters</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('model')->hasErrors()) {?>
      <div class="has-error">
              <?php foreach ($form->getElement('model')->getMessages() as $message) { ?>
                  <p class="help-block"><?php echo $this->escape($message); ?></p>
              <?php } ?>
          </div>
      <?php } ?>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="type">Part Type</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('type')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter product\'s type',
          'id'=>'type',
          'required'=>'required'
      ));
      ?>
  
  <span class="help-block">min 3 max 10 characters</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('type')->hasErrors()) {?>
      <div class="has-error">
              <?php foreach ($form->getElement('type')->getMessages() as $message) { ?>
                  <p class="help-block"><?php echo $this->escape($message); ?></p>
              <?php } ?>
          </div>
      <?php } ?>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="price">Price</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('price')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter product\'s price',
          'id'=>'price',
          'required'=>'required'
      ));
      ?>
      
  <span class="help-block">0.00</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('price')->hasErrors()) {?>
<div class="has-error">
	<?php foreach ($form->getElement('price')->getMessages() as $message) {?>
	<p class="help-block"><?php echo $this->escape($message);?></p>
	<?php }?>
</div>
<?php }?>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="discount">Discount</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('discount')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter discount for product',
          'id'=>'discount',
          //'required'=>'required'
      ));
      ?>
  
  <span class="help-block">10%</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('discount')->hasErrors()) {?>
      <div class="has-error">
              <?php foreach ($form->getElement('discount')->getMessages() as $message) { ?>
                  <p class="help-block"><?php echo $this->escape($message); ?></p>
              <?php } ?>
          </div>
      <?php } ?>
  </div>
</div>


<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="quantity">Quantity</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('quantity')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter product\'s quantity',
          'id'=>'quantity',
          'required'=>'required'
      ));
      ?>
      
  <span class="help-block">0.00</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('quantity')->hasErrors()) {?>
<div class="has-error">
	<?php foreach ($form->getElement('quantity')->getMessages() as $message) {?>
	<p class="help-block"><?php echo $this->escape($message);?></p>
	<?php }?>
</div>
<?php }?>
  </div>
</div>

<!-- Text Area input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="description">Description</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('description')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter product\'s description',
          'id'=>'description',
          'rows'=> 5
      ));
      ?>
  
  <span class="help-block">min 3 max 255 characters</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('description')->hasErrors()) { ?>
          <div class="has-error">
              <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                  <p class="help-block"><?php echo $this->escape($message); ?></p>
              <?php } ?>
          </div>
      <?php } ?>
  </div>
</div>
<!-- Photo -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="product_photo">Photo</label>
                            <div class="col-md-4">    

                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->productImgUrl($this->product); ?>">
                                    </a>
                                    <span class="help-block">Change Photo</span>   
                                </div>

                                <input type="file" name="product_photo" id="product_photo" class="btn btn-default btn-file">

                            </div>

                        </div>

<!-- Button (Double) -->
<div class="form-group text-right">
  <label class="col-md-4 control-label" for="new_product_cancel"></label>
  <div class="col-md-8">
    <a href="<?php echo $this->url(array('controller' =>'admin_products', 'action'=>'index'), 'default', true); ?>" id="new_product_cancel" name="new_product_cancel" class="btn btn-default">Cancel</a>
    <button type="submit" id="new_product_submit" name="new_product_submit" class="btn btn-success">Save</button>
  </div>
</div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>