<?php
$sitemapPage = $this->sitemapPage;
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
$systemMessages = $this->systemMessages;
$this->headTitle($sitemapPage['title']);
//$this->headMeta()->appendName('description', $sitemapPage['description']);
?>
<main>
    <div class="container">

        <article>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                <?php foreach ($this->breadcrumb as $breadcrumb) { ?>
                    <li><a href=""><?php echo $breadcrumb['short_title']; ?></a></li>
                <?php } ?>
            </ol>
        </article>
        <div class="header-a">
            
        </div>
        <main class="contactUs">
	    <section class="googleMap">
		<div class="mapWrapper">
		    <div id='gmap_canvas' ></div>		  
		</div>

		<div class="formWrapp">
		    <div class="formContact">
			<div class="row">
			    <div class="col-lg-6">
				<div class="adress">
                    <h2><p>Contact Us</p> </h2>
                    <h3><p>011 783 99 99</p></h3>
                    <p>Gospodara Vucica 33, 11000 Belgrade, Serbia</p>
                </div>
			    </div>
			</div>
			 <?php 
                    if($systemMessages == "init"){ ?>
                        <form method="post" action="" id="contact-form">
                            <input type="hidden" name="task" value="contact">
			<form class="form-group">
			    <div class="row">
				<div class="col-lg-6">
				    <div class="moja-margina">
					<?php
                            echo $form->getElement('name')->setAttribs(array(
                                'class' => 'form-control input-md',
                                'placeholder' => 'enter your name',
                                'id' => 'name',
                                'required' => 'required'
                            ));
                            ?>
                             <?php if ($form->getElement('name')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                            <?php } ?> 
				    </div><!-- /input-group -->
				</div><!-- /.col-lg-6 -->
				<div class="col-lg-6">
				    <div class="moja-margina2">
					<?php
                            echo $form->getElement('email')->setAttribs(array(
                                'class' => 'form-control input-md',
                                'placeholder' => 'enter your email',
                                'id' => 'email',
                                'required' => 'required'
                            ));
                            ?>
                             <?php if ($form->getElement('email')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                            <?php } ?> 
				    </div><!-- /input-group -->
				</div><!-- /.col-lg-6 -->

				<div class="col-xs-12">
				    <div class="moja-margina3">
					<input type="submit" value="Send Message" class="btn btn-primary">
				    </div><!-- /input-group -->
				</div>
                                
			    </div><!-- /.row -->
			</form>
                        
                        <?php }else{
                        if($systemMessages == "Error"){
                            echo "Doslo je do greske prilikom slanja poruke";
                        }
                        if($systemMessages == "Success"){
                            echo "Uspesno poslata poruka";
                        }
                        }
                    
                        ?>
                            
		    </div>
		</div>
	    </section>
	               
	</main>
    </div>
</main>