<?php
$this->headTitle('Suppliers - New Supplier');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));//za ispis gresaka u formi
?>
<div class="page-header">
    <h1>Suppliers <small>New Supplier</small></h1>
</div>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12"> 
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href='<?php echo $this->url(array('controller'=>'admin_suppliers', 'action'=>'index'), 'default', true) ?>' 
                       class="btn btn-default"
                       ><i class="glyphicon glyphicon-arrow-left"></i>Back to all suppliers</a>
                
</div></div>
            <div class="panel-body">
               <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                   <input type="hidden" name="task" value="save">
<fieldset>

<!-- Form Name -->
<legend>New Supplier</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="name">Supplier Name</label>  
  <div class="col-md-4">
      <?php
      echo $form->getElement('name')->setAttribs(array(
          'class' => 'form-control input-md',
          'placeholder'=>'enter supplier\'s name',
          'id'=>'name',
          'required'=>'required'
      ));
      ?>
  <span class="help-block">min 3 max 255 characters</span>  
  </div>
  <div class="col-md-4">
      <?php if ($form->getElement('name')->hasErrors()) { ?>
          <div class="has-error">
              <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                  <p class="help-block"><?php echo $this->escape($message); ?></p>
              <?php } ?>
          </div>
      <?php } ?> 
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
    <label class="col-md-4 control-label" for="description">Description</label>
    <div class="col-md-4">                     
        <?php
        echo $form->getElement('description')->setAttribs(array(
            'class' => 'form-control',
            'id' => 'description',
            'rows'=> 12
        ));
        ?>
    </div>
    <div class="col-md-4">
        <?php if ($form->getElement('description')->hasErrors()) { ?>
            <div class="has-error">
                <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                <?php } ?>
            </div>
        <?php } ?>  
    </div>
</div>
<div class="form-group">
    <label class="col-md-4 control-label" for="supplier_photo">Photo</label>
    <div class="col-md-4">                     
        <input type="file" name="supplier_photo" id="supplier_photo" class="btn btn-default btn-file">
    </div>
    <div class="col-md-4">
        <?php if ($form->getElement('supplier_photo')->hasErrors()) { ?>
            <div class="has-error">
                <?php foreach ($form->getElement('supplier_photo')->getMessages() as $message) { ?>
                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                <?php } ?>
            </div>
        <?php } ?>  
    </div>
</div>

<!-- Button (Double) -->
<div class="form-group text-right">
  <label class="col-md-4 control-label" for="new_supplier_cancel"></label>
  <div class="col-md-8">
    <a href="<?php echo $this->url(array('controller' =>'admin_suppliers', 'action'=>'index'), 'default', true); ?>" id="new_supplier_cancel" name="new_supplier_cancel" class="btn btn-default">Cancel</a>
    <button type="submit" id="new_supplier_submit" name="new_supplier_submit" class="btn btn-success">Save</button>
  </div>
</div>

</fieldset>
</form>

            </div>
        </div>
    </div>
</div>
