

<?php
Zend_Layout::getMvcInstance()->disableLayout();//gasimo layout
$enabled= $this->enabledSuppliers;//prenos iz poslovne logike
$allSuppliers = $this->allSuppliers;
?>


        <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->escape($enabled . ' / ' .$allSuppliers );?></div>
                                    <div>Enabled/All</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->url(array('controller'=>'admin_suppliers'), "default", true); ?>">
                            <div class="panel-footer">
                                <span class="pull-left">View Details about Suppliers</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
</div>